name: CI/CD for simple-http-checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Display Python and uv versions
        run: |
          python --version
          uv --version

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run Ruff linter
        run: |
          uv run ruff check .

      - name: Run Ruff formatter check
        run: |
          uv run ruff format --check .

      - name: Run mypy type checking
        run: |
          uv run mypy src/

      - name: Run bandit security scan
        run: |
          uv run bandit -r src/

      - name: Run pytest
        run: |
          uv run pytest -v